default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_bin
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USERNAME") { 'root' } %>
  password: <%= ENV.fetch("DB_ROOT_PASSWORD") { '' } %>
  host: <%= ENV.fetch("DB_HOST") { 'localhost' } %>

development:
  <<: *default
  database: restful_api_rails_development

test:
  <<: *default
  database: restful_api_rails_test

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: restful_api_rails_production
