source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby file: '.ruby-version'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 8.0.2'
# Use Puma as the app server
gem 'puma', '~> 6.5.0'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use Active Model has_secure_password
gem 'bcrypt', '~> 3.1.20'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '~> 1.18.4', require: false

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
# gem 'rack-cors'

# JSON web tokens
gem 'jwt', '~> 2.10.2'

# Active model serializers
gem 'active_model_serializers', '~> 0.10.14'

# pagination
gem 'will_paginate', '~> 4.0.1'

# environmental variables
gem 'dotenv-rails', '~> 3.1.8'

gem 'nokogiri', '~> 1.18.9'

gem 'net-smtp', '~> 0.5.0'

# The Observer pattern provides a simple mechanism for one object to inform a set of interested third-party objects when its state changes.
gem 'observer', '~> 0.1.2'

# Data structure, similar to a Hash, that allows the definition of arbitrary attributes with their accompanying values
gem 'ostruct', '~> 0.6.3'

# A foreign function interface (FFI) is a mechanism by which a program written in one programming language can call routines or make use of services written or compiled in another one
gem 'ffi', '~> 1.17.2'

group :development, :test do
  # Use MySQL as the database for Active Record
  gem 'mysql2', '~> 0.5.6'
  # Debug tool used with binding.irb
  # 'debug/prelude' option enables debug gem only if debugger is called. Otherwise, it is deactivated.
  # [Ref] https://ruby.github.io/irb/#label-Debugging+with+IRB
  # [Ref] https://github.com/ruby/debug#debug-command-on-the-debug-console
  # [Ref] https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem 'debug', platforms: %i[ mri windows ], require: 'debug/prelude'
end

group :development do
  gem 'listen', '~> 3.9.0'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring', '~> 4.2.1'
  gem 'spring-watcher-listen', '~> 2.1.0'
  # Static code analysis for security vulnerabilities
  gem 'brakeman', '~> 7.0.2', require: false
end

group :test do
  # 'factory_bot_rails' cames not to behave right in 5.0 or more
  gem 'factory_bot_rails', '~> 6.4.3'
  gem 'rspec-rails', '~> 7.1.1'
  gem 'faker', '~> 3.5.2'
  gem 'shoulda-matchers', '~> 6.4.0'
  gem 'database_cleaner', '~> 2.1.0'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
