source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby file: '.ruby-version'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 8.0.2'
# Use Puma as the app server
gem 'puma', '~> 6.5.0'
# The original asset pipeline for Rails [https://github.com/rails/sprockets-rails]
gem 'sprockets-rails', '~> 3.5.2'
# Transpile app-like JavaScript. Read more: https://github.com/rails/webpacker
gem 'webpacker', '~> 5.4.4'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbo-rails', '~> 2.0.16'
# Use Sass to process CSS
gem 'sassc-rails', '~> 2.1.2'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.13.0'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 5.3.0'
# Use Active Model has_secure_password
# gem 'bcrypt', '~> 3.1.20'

# Use Active Storage variant
gem 'image_processing', '~> 1.13.0'

gem 'active_storage_validations', '~> 1.4.0'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '~> 1.18.4', require: false

# environmental variables
gem 'dotenv-rails', '~> 3.1.8'

# OAuth
gem 'omniauth', '~> 2.1.3'
gem 'omniauth-github', '~> 2.0.1'
gem 'omniauth-rails_csrf_protection', '~> 1.0.2'

# Locale
gem 'rails-i18n', '~> 8.0.1'

# Pagination
gem 'kaminari', '~> 1.2.2'

# SearchForm
gem 'ransack', '~> 4.2.1'

gem 'rexml', '~> 3.4.1'

gem 'nokogiri', '~> 1.18.9'

# YAML parser
gem 'psych', '~> 5.2.2'

gem 'net-smtp', '~> 0.5.0'

# The Observer pattern provides a simple mechanism for one object to inform a set of interested third-party objects when its state changes.
gem 'observer', '~> 0.1.2'

# Data structure, similar to a Hash, that allows the definition of arbitrary attributes with their accompanying values
gem 'ostruct', '~> 0.6.3'

# A foreign function interface (FFI) is a mechanism by which a program written in one programming language can call routines or make use of services written or compiled in another one
gem 'ffi', '~> 1.17.2'

group :development, :test do
  # Use mysql as the database for Active Record
  gem 'mysql2', '~> 0.5.6'
  # Debug tool used with binding.irb
  # 'debug/prelude' option enables debug gem only if debugger is called. Otherwise, it is deactivated.
  # [Ref] https://ruby.github.io/irb/#label-Debugging+with+IRB
  # [Ref] https://github.com/ruby/debug#debug-command-on-the-debug-console
  # [Ref] https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem 'debug', platforms: %i[ mri windows ], require: 'debug/prelude'
end

group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'web-console', '~> 4.2.1'
  gem 'listen', '~> 3.9.0'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring', '~> 4.2.1'
  # Static code analysis for security vulnerabilities
  gem 'brakeman', '~> 7.0.2', require: false
end

group :test do
  gem 'factory_bot_rails', '~> 6.4.3'
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '~> 3.40.0'
  gem 'selenium-webdriver', '~> 4.27.0'
  gem 'matrix', '~> 0.4.2'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
